spring:
  datasource:
    url: jdbc:mysql://localhost/myproject?serverTimezone=GMT%2B8 #增加时区
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver  #com.mysql.cj.jdbc.Driver  #新的驱动名称   com.mysql.jdbc.Driver 之后被弃用
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: true
server:
  port: 8080