server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost/myproject?serverTimezone=GMT%2B8&useSSL=false #增加时区
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver  #com.mysql.cj.jdbc.Driver  #新的驱动名称   com.mysql.jdbc.Driver 之后被弃用
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#    控制台显示SQL
    show-sql: true
  redis:
    host: 10.211.55.3
    port: 6379
    database: 0
    timeout: 1000

  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
  mvc:
    date-format: yyyy-MM-dd





